"""empty message

Revision ID: 34c0e0854cb7
Revises: 17259b5f2964
Create Date: 2014-05-13 01:54:54.462050

"""

# revision identifiers, used by Alembic.
revision = '34c0e0854cb7'
down_revision = '17259b5f2964'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readinglistitems',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('read', 'unread'), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'user_id')
    )
    op.alter_column(u'authors', 'date_created',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column(u'notes', 'date_created',
               existing_type=sa.DATETIME(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'notes', 'date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column(u'authors', 'date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_table('readinglistitems')
    ### end Alembic commands ###
