"""empty message

Revision ID: 798391ec340
Revises: 4f7ae29cd6b9
Create Date: 2014-05-01 01:03:03.397245

"""

# revision identifiers, used by Alembic.
revision = '798391ec340'
down_revision = '4f7ae29cd6b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Unicode(length=5000), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    ### end Alembic commands ###
